"""add book_id index in review table

Revision ID: a4ba5fde4bbe
Revises: 12f56b1c324d
Create Date: 2025-06-29 22:08:05.019860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ba5fde4bbe'
down_revision: Union[str, Sequence[str], None] = '12f56b1c324d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_reviews_book_id'), 'books_reviews', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_reviews_book_id'), table_name='books_reviews')
    # ### end Alembic commands ###
